FROM ubuntu:22.04

# Instalar Icecast
RUN apt-get update && \
    apt-get install -y icecast2 && \
    rm -rf /var/lib/apt/lists/*

# Crear directorio de configuración
RUN mkdir -p /etc/icecast2

# Copiar configuración
COPY icecast.xml /etc/icecast2/icecast.xml

# Exponer puerto
EXPOSE 8000

# Iniciar Icecast
CMD ["icecast2", "-c", "/etc/icecast2/icecast.xml"]